package com.koimsurai.fakegps.ui.theme

import androidx.compose.ui.graphics.Color

// Dark-first brand palette. The map underneath is full-colour OSM, so the app's own surfaces are
// deep, near-neutral greens that stay readable on top of it, with one vivid mint accent reserved
// for the active/primary action and a coral accent for anything that stops or destroys.

// --- Dark (primary target) ---
val brandPrimaryDark = Color(0xFF5BE9B0)
val brandOnPrimaryDark = Color(0xFF00382A)
val brandPrimaryContainerDark = Color(0xFF00513C)
val brandOnPrimaryContainerDark = Color(0xFF7FFFCB)
val brandSecondaryDark = Color(0xFFB0CCC0)
val brandOnSecondaryDark = Color(0xFF1C352C)
val brandSecondaryContainerDark = Color(0xFF334B42)
val brandOnSecondaryContainerDark = Color(0xFFCCE9DC)
val brandTertiaryDark = Color(0xFFFFB59B)
val brandOnTertiaryDark = Color(0xFF561F06)
val brandTertiaryContainerDark = Color(0xFF74331A)
val brandOnTertiaryContainerDark = Color(0xFFFFDBCE)
val brandBackgroundDark = Color(0xFF0B0F0E)
val brandOnBackgroundDark = Color(0xFFE3E9E5)
val brandSurfaceDark = Color(0xFF0B0F0E)
val brandOnSurfaceDark = Color(0xFFE3E9E5)
val brandSurfaceContainerLowDark = Color(0xFF111816)
val brandSurfaceContainerDark = Color(0xFF151C1A)
val brandSurfaceContainerHighDark = Color(0xFF1D2523)
val brandSurfaceContainerHighestDark = Color(0xFF273230)
val brandSurfaceVariantDark = Color(0xFF3F4945)
val brandOnSurfaceVariantDark = Color(0xFFB6C2BC)
val brandOutlineDark = Color(0xFF89938E)
val brandOutlineVariantDark = Color(0xFF3F4945)
val brandErrorDark = Color(0xFFFFB4AB)
val brandOnErrorDark = Color(0xFF690005)
val brandErrorContainerDark = Color(0xFF93000A)
val brandOnErrorContainerDark = Color(0xFFFFDAD6)

// --- Light ---
val brandPrimaryLight = Color(0xFF006B51)
val brandOnPrimaryLight = Color(0xFFFFFFFF)
val brandPrimaryContainerLight = Color(0xFF8FF7C8)
val brandOnPrimaryContainerLight = Color(0xFF002117)
val brandSecondaryLight = Color(0xFF4B635A)
val brandOnSecondaryLight = Color(0xFFFFFFFF)
val brandSecondaryContainerLight = Color(0xFFCCE9DC)
val brandOnSecondaryContainerLight = Color(0xFF072019)
val brandTertiaryLight = Color(0xFF9A4523)
val brandOnTertiaryLight = Color(0xFFFFFFFF)
val brandTertiaryContainerLight = Color(0xFFFFDBCE)
val brandOnTertiaryContainerLight = Color(0xFF380D00)
val brandBackgroundLight = Color(0xFFF5FBF7)
val brandOnBackgroundLight = Color(0xFF161D1A)
val brandSurfaceLight = Color(0xFFF5FBF7)
val brandOnSurfaceLight = Color(0xFF161D1A)
val brandSurfaceContainerLowLight = Color(0xFFEFF6F1)
val brandSurfaceContainerLight = Color(0xFFE9F1EC)
val brandSurfaceContainerHighLight = Color(0xFFE4ECE7)
val brandSurfaceContainerHighestLight = Color(0xFFDEE6E1)
val brandSurfaceVariantLight = Color(0xFFDBE5DF)
val brandOnSurfaceVariantLight = Color(0xFF3F4945)
val brandOutlineLight = Color(0xFF6F7975)
val brandOutlineVariantLight = Color(0xFFBFC9C3)
val brandErrorLight = Color(0xFFBA1A1A)
val brandOnErrorLight = Color(0xFFFFFFFF)
val brandErrorContainerLight = Color(0xFFFFDAD6)
val brandOnErrorContainerLight = Color(0xFF410002)
